services:
  bp-apple-checker:
    image: bp-apple-checker
    environment:
      - FREQUENCY=5
      - PUSHOVER_USER_KEY=your_user_key
      - PUSHOVER_API_TOKEN=your_api_token
      - STORE_NUMBER=your_store_number # for reference: https://applestorefronts.appspot.com/
      - SEARCH_NEARBY= true #true or false
    ports:
      - "3767:3767"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped